// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 18.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'sanalira_case';

  static const String assets_icons_Layer_2_svg = 'assets/icons/Layer 2.svg';
  static const String sanalira_case$assets_icons_Layer_2_svg = 'packages/sanalira_case/assets/icons/Layer 2.svg';

  static const String assets_icons_Layer_1_svg = 'assets/icons/Layer_1.svg';
  static const String sanalira_case$assets_icons_Layer_1_svg = 'packages/sanalira_case/assets/icons/Layer_1.svg';

  static const String assets_icons_Ziraat_Bankasi_logo_png = 'assets/icons/Ziraat_Bankasi_logo.png';
  static const String sanalira_case$assets_icons_Ziraat_Bankasi_logo_png = 'packages/sanalira_case/assets/icons/Ziraat_Bankasi_logo.png';

  static const String assets_icons_akbank_png = 'assets/icons/akbank.png';
  static const String sanalira_case$assets_icons_akbank_png = 'packages/sanalira_case/assets/icons/akbank.png';

  static const String assets_icons_albaraka_png = 'assets/icons/albaraka.png';
  static const String sanalira_case$assets_icons_albaraka_png = 'packages/sanalira_case/assets/icons/albaraka.png';

  static const String assets_icons_bell_svg = 'assets/icons/bell.svg';
  static const String sanalira_case$assets_icons_bell_svg = 'packages/sanalira_case/assets/icons/bell.svg';

  static const String assets_icons_garanti_jpg = 'assets/icons/garanti.jpg';
  static const String sanalira_case$assets_icons_garanti_jpg = 'packages/sanalira_case/assets/icons/garanti.jpg';

  static const String assets_icons_hut_svg = 'assets/icons/hut.svg';
  static const String sanalira_case$assets_icons_hut_svg = 'packages/sanalira_case/assets/icons/hut.svg';

  static const String assets_icons_kuveyt_png = 'assets/icons/kuveyt.png';
  static const String sanalira_case$assets_icons_kuveyt_png = 'packages/sanalira_case/assets/icons/kuveyt.png';

  static const String assets_icons_left_arrow_svg = 'assets/icons/left-arrow.svg';
  static const String sanalira_case$assets_icons_left_arrow_svg = 'packages/sanalira_case/assets/icons/left-arrow.svg';

  static const String assets_icons_main_icon_png = 'assets/icons/main_icon.png';
  static const String sanalira_case$assets_icons_main_icon_png = 'packages/sanalira_case/assets/icons/main_icon.png';

  static const String assets_icons_qnb_png = 'assets/icons/qnb.png';
  static const String sanalira_case$assets_icons_qnb_png = 'packages/sanalira_case/assets/icons/qnb.png';

  static const String assets_icons_settings_svg = 'assets/icons/settings.svg';
  static const String sanalira_case$assets_icons_settings_svg = 'packages/sanalira_case/assets/icons/settings.svg';

  static const String assets_icons_transaction_svg = 'assets/icons/transaction.svg';
  static const String sanalira_case$assets_icons_transaction_svg = 'packages/sanalira_case/assets/icons/transaction.svg';

  static const String assets_icons_turkey_svg = 'assets/icons/turkey.svg';
  static const String sanalira_case$assets_icons_turkey_svg = 'packages/sanalira_case/assets/icons/turkey.svg';

  static const String assets_icons_user_svg = 'assets/icons/user.svg';
  static const String sanalira_case$assets_icons_user_svg = 'packages/sanalira_case/assets/icons/user.svg';

  static const String assets_icons_vakifbank_png = 'assets/icons/vakifbank.png';
  static const String sanalira_case$assets_icons_vakifbank_png = 'packages/sanalira_case/assets/icons/vakifbank.png';

  static const String assets_images_login_wp_png = 'assets/images/login_wp.png';
  static const String sanalira_case$assets_images_login_wp_png = 'packages/sanalira_case/assets/images/login_wp.png';
}
